### ISSUE TITLE
Persist state when refreshing page in browser

### ISSUE THREAD

**Issue by GerbenVersluis** [zendesk/zopim-chat-web-sdk-sample-app#19]
Hi.

There are users refreshing the page which results in losing the current chat. They have to open a new chat to get back in touch with customer-support. It would be a welcomed feature to persist the state of the chat i.e. sessionstorage. That way the chat could be stored untill the browser is fully closed. I couldn't find this feature in the current reactjs-demo.

**Comment by vivekjains** [comment]
Following this sample app, we are trying to create custom widget using Vuejs & Vuex for our PWA

But whenever user refreshes/reloads the page, visitor information gets changed (checked under "visitor_update" event listener). 

Is there a way to persist the same if not done by the SDK already so that it wont create a new session on the Zopim dashboard everytime??

**Comment by rshokrizadeh** [comment]
Thanks for posting @vivekjains and @GerbenVersluis. Is this happening when you test the code locally via localhost? 

Since the visitor cookie is based on the domain, this is expected behaviour for localhost. To get around this, use an IP address or domain and it should not disconnect.

If you are not using local host and are still experiencing disconnections, let us know and we can investigate it further.

**Comment by vivekjains** [comment]
@rshokrizadeh Great! that worked. 
A note about visitor cookie in documentation would definitely help developers.

**Comment by rshokrizadeh** [comment]
Glad it was an easy fix :) I will work on adding info to the repo about limitations of using local host.

**Comment by davinc** [comment]
We faced the same issue, spent too many hours fixing it. This should be documented in the support documentation of the sample app.
