### ISSUE TITLE
Export the chat widget as a React component

### ISSUE THREAD

**Issue by dangreenisrael** [zendesk/zopim-chat-web-sdk-sample-app#21]
It would be super awesome if you exported the chat widget as a react component that we could just use in our app 😄

**Comment by tgohn** [comment]
Hi @dangreenisrael , 

Currently we do not have any immediate plan to export the project as an easy consumable React component :(

The project is created as an sample implementation of our `chat-web-sdk`.
So depending on your app's setup, you could achieve tighter and more performance implementation.
For example, use your own Redux store instead of separate store, or relying on your own theming framework and business layer for more awesome user experience. 😄

**Comment by dangreenisrael** [comment]
Thanks @tgohn
