### ISSUE TITLE
Chat Event: This should be emitted at a frequency

### ISSUE THREAD

**Issue by someguynamedmatt** [zendesk/zopim-chat-web-sdk-sample-app#3]
Currently, if you want to get the queue length with the 'chat.wait_queue' event you can only get it on the initial connection. After which, the event is never emitted again. Ideally this should be sent every, say, 60 seconds so that the API ingestor can get updates on the queue status.

**Comment by junyi** [comment]
Hi Matt,

Thanks for your feedback and for trying out the Web SDK.

At the moment, this is the expected behavior as we also display the queue message once to the visitor in the default chat widget when they are put into the wait queue. This message is not updated subsequently even if the queue length changes.

**Edit**: This behavior is also documented for the `chat.wait_queue` event: https://api.zopim.com/web-sdk/#chat-wait_queue-chat-event-type.

We will consider enhancing the widget queue message in the future but it is currently not planned for the next 6 months.

Thanks,
Jun Yi
